version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: all-contributors-cli
    versions:
    - "< 4.12, >= 4.11.0"
  - dependency-name: babel-loader
    versions:
    - "< 7.2, > 7.1.1"
  - dependency-name: eslint
    versions:
    - "< 4.19, >= 4.18.a"
  - dependency-name: eslint
    versions:
    - "< 4.20, >= 4.19.0"
  - dependency-name: eslint
    versions:
    - "< 5.4, >= 5.3.a"
  - dependency-name: eslint-config-airbnb
    versions:
    - "< 16.2, >= 16.1.0.a"
  - dependency-name: eslint-config-airbnb
    versions:
    - "< 17.1, >= 17.0.a"
  - dependency-name: eslint-loader
    versions:
    - "< 2.1, >= 2.0.0.a"
  - dependency-name: eslint-loader
    versions:
    - "< 2.2, >= 2.1.a"
  - dependency-name: eslint-plugin-import
    versions:
    - "< 2.11, >= 2.10.0"
  - dependency-name: eslint-plugin-import
    versions:
    - "< 2.13, >= 2.12.a"
  - dependency-name: eslint-plugin-import
    versions:
    - "< 2.14, >= 2.13.a"
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - "< 6.1, >= 6.0.0.a"
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - "< 6.2, >= 6.1.a"
  - dependency-name: eslint-plugin-react
    versions:
    - "< 7.11, >= 7.10.a"
  - dependency-name: eslint-plugin-react
    versions:
    - "< 7.8, >= 7.7.0.a"
  - dependency-name: eslint-plugin-react
    versions:
    - "< 7.9, >= 7.8.a"
  - dependency-name: fetch-mock
    versions:
    - "< 6.5, >= 6.4.a"
  - dependency-name: fetch-mock
    versions:
    - "< 6.6, >= 6.5.a"
  - dependency-name: jest
    versions:
    - "< 22.5, >= 22.4.a"
  - dependency-name: jest
    versions:
    - "< 23.5, >= 23.4.a"
  - dependency-name: rollup
    versions:
    - "< 0.60, >= 0.59.a"
  - dependency-name: rollup-plugin-babel
    versions:
    - "< 3.1, >= 3.0.a"
  - dependency-name: rollup-plugin-commonjs
    versions:
    - "< 9.2, > 9.1.0"
  - dependency-name: rollup-plugin-conditional
    versions:
    - "< 2.2, >= 2.1.a"
  - dependency-name: rollup-plugin-eslint
    versions:
    - "< 5.1, >= 5.0.a"
  - dependency-name: rollup-plugin-json
    versions:
    - "< 3.1, >= 3.0.a"
  - dependency-name: rollup-plugin-node-globals
    versions:
    - "< 1.3, >= 1.2.a"
  - dependency-name: rollup-plugin-uglify
    versions:
    - "< 4.1, >= 4.0.a"
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: rollup-plugin-filesize
    versions:
    - 9.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: nock
    versions:
    - 13.0.6
    - 13.0.7
    - 13.0.9
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
